[package]
name = "red4-conflicts"
version = "0.2.0"

[dependencies]
egui = "0.23.0"
eframe = { version = "0.23.0", default-features = false, features = [
  "default_fonts", # Embed the default egui fonts.
  "glow",          # Use the glow rendering backend. Alternative: "wgpu".
  "persistence",   # Enable restoring app state when restarting the app.
] }
log = "0.4"
rfd = "0.12"
serde = { version = "1", features = ["derive"] }
byteorder = "1.5"
env_logger = "0.10"
fnv = "1.0"
csv = "1.3"

[patch.crates-io]

[build-dependencies.cmake]
version = "0.1"
