name: Check

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # automated checks
  check:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: true
      matrix:
        os: [windows-latest]
        build_type: [release]
        target: [tweak-doxygen, red4-tweak-browser, red4-conflicts, "red4-update"]

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        cd ${{ matrix.target }}
        cargo build --${{ matrix.build_type }}
    - name: Run tests
      run: |
        cd ${{ matrix.target }}
        cargo test